/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define TIM2_IRQ 28
#define I2C1_IRQ 31

uint32_t *pNVIC_ISERBase = (uint32_t*)0xE000E100;
uint32_t *pNVIC_ISPRBase = (uint32_t*)0XE000E200;
uint32_t *pNVIC_IPRBase =  (uint32_t*)0xE000E400;

void set_interrupt_priority(uint8_t IRQNumber, uint8_t priority)
{
	uint8_t iprx = IRQNumber / 4;
	uint32_t *ipr = pNVIC_IPRBase + iprx;
	uint8_t pos = (IRQNumber % 4) * 8;

	*ipr &= ~(0xFF << pos);
	*ipr |= (priority << pos);
}

void set_interrupt_pending(uint8_t IRQNumber)
{

	*pNVIC_ISPRBase |= (1 << IRQNumber);
}

void enable_interrupt(uint8_t IRQNumber)
{
	*pNVIC_ISERBase |= (1 << IRQNumber);
}

int main(void)
{

	set_interrupt_priority(TIM2_IRQ, 0x80);
	set_interrupt_priority(I2C1_IRQ, 0x70);

	set_interrupt_pending(TIM2_IRQ);

	enable_interrupt(I2C1_IRQ);
	enable_interrupt(TIM2_IRQ);

    /* Loop forever */
	for(;;);
}

void TIM2_IRQHandler(void)
{
	printf("[TIM2_IRQHandler] ISR\n");
	set_interrupt_pending(I2C1_IRQ);
}

void I2C1_EV_IRQHandler(void)
{
	printf("[I2C1_EV_IRQHandler] ISR\n");

}
